GiftedMessenger.js
Multiple events propagating, ensure only one goes through to not throw exception.
=> [GiftedMessenger] Fix issue with RN 0.16.0

GiftedMessenger.js
Bubbles now look like native IOS messaging bubbles with variable with
Username positioned more appealingly
For reference:
=> Style changes for bubbles

Bubble.js, ErrorButton.js, GiftedMessenger.js, Message.js
=> Split Message into seperate component.

Message.js
Simply pass a `view` property with the rowData to render a custom component, defaults to Bubble. This is a simple solution that provides a lot of flexibility.
should close out #2
=> Allow passing message component as prop

GiftedMessenger.js
scrollWithoutAnimationTo(vertical, horizontal)
=> scrollWithoutAnimationTo(vertical, horizontal)

GiftedMessenger.js
Hi,
It is a fix to #60.
Please let me know if you need anything else, or if something is wrong.
=> fix onKeyboardWillHide & onKeyboardWillShow not working on Android

Bubble.js, GiftedMessenger.js, README.md
Resolves #72 
Resolves #73
Resolves #65 
For those who want to render content based on specific rowData attributes, I exposed the full rowData to the renderCustomText function.
Text input hide/show needs to be dynamic, so I changed the animated height to make it work.
Added autoScroll props as a new message array comes in, it'll auto scroll to bottom.
=> Expose full rowData to renderCustomText and add dynamic hide/show text input

GiftedMessenger.js
=> Fix some typo, solved issue #83

GiftedMessenger.js, README.md
p.ex. an attach image button, etc.
=> Add leftControlBar prop to display buttons left of the text input field

GiftedMessenger.js
Add setTextInputValue method and refactor some code that seems redundant. This allows users to access the value of the text input.
=> [TextInput] Add setTextInputValue method

README.md
add the default about “(rowData) => {}”
=> fix the document about onMessageLongPress

GiftedMessenger.js
Sometimes it could be useful - to set initial text input value. For my application - I open dialog with formating message
=> Added initial text to props

Bubble.js, ErrorButton.js, GiftedMessenger.js, GiftedMessengerExample/GiftedMessengerContainer.js, GiftedMessengerExample/Navigation.js, GiftedMessengerExample/index.android.js, GiftedMessengerExample/index.ios.js, Message.js, package.json
react and react-native dependencies need to be split
=> Support RN 0.25

.gitignore, GiftedMessenger.js, README.md, package.json
Allow custom rendering for text input
=> Allow custom rendering for text input

src/Bubble.js
=> Fix renderMessageImage/renderMessageText not overriding the default.

README.md
It’s hard to understand where exactly the attribute goes without more context.
=> add more XML context to android installation

package.json, src/GiftedChat.js, src/Message.js, src/MessageContainer.js
Moving hash to each message should allow MessageContainer to rerender when messages are not changed.
Use ListView with InvertibleListView to easily support a lot of messages and have renderFooter, renderHeader etc.
=> Move hash to single message from all messages

src/Actions.js
Add prop optionTintColor for ActionSheet options text
=> [Request] Add prop for tintColor for ActionSheet in Actions #185

README.md, src/MessageContainer.js
for some purpose, we want to listen event on ListView, like `onScroll`, `onLayout`.... 
such as animate a view when list view in scroll
=> custom ListView props support

example/package.json, package.json, src/GiftedChat.js, src/MessageContainer.js
This will only work with the latest RN version because the keyboardShouldPersistTaps prop was changed to enum
=> Remove keyboard api dependency and add optional keyboardShouldPersistTaps prop

README.md, src/GiftedChat.js
I added the correct prop validation for the keyboardShouldPersistTaps prop to accept any of the enum values. 
I also updated the Readme to reflect this changes
=> Update prop validation for keyboardShouldPersistTaps

example/ios/GiftedChat.xcodeproj/project.pbxproj, example/ios/GiftedChat.xcodeproj/xcshareddata/xcschemes/GiftedChat.xcscheme, example/ios/GiftedChat/Images.xcassets/AppIcon.appiconset/Contents.json, example/ios/GiftedChat/Info.plist, example/package.json
@kfiroo So in order to get the new keyboard props working, we need to update to the latest RN version. I managed to build GC with the latest RN making some changes on the xcode project. 
Here are all the changes we need to make it work with RN 0.40
I'm not sure how you want to handle this, I just create the PR, let me know if you think we should do something else.
This includes the changes in the info.plist to make the camera work as well
=> Update RN version to 0.40

package.json, src/GiftedChat.js
Fixes https://github.com/FaridSafi/react-native-gifted-chat/issues/215
=> fixed chat height bug

README.md, src/Avatar.js
Currently, the Avatar component render the avatar of a message on the last consecutive message from the user.
This prop allows users to change this behavior, so that the avatar is rendered on the first message.
The default value is false, which keeps the current behavior.
=> Added "renderAvatarOnTop" prop to Avatar.js

README.md, src/Avatar.js, src/Bubble.js
This is the rebased version of https://github.com/FaridSafi/react-native-gifted-chat/pull/264, with some minor nits and cleanup.
Verified on iOS after rebase.
=> Add `onPressAvatar` prop (rebased)

src/GiftedChat.js
Solves https://github.com/FaridSafi/react-native-gifted-chat/issues/377
=> Removed InteractionManager.runAfterInteractions during init

src/MessageImage.js
Very minor cleanup just based on reading release notes :slightly_smiling_face:
=> Remove dead code introduced by https://github.com/FaridSafi/react-native-gifted-chat/pull/467

README.md, src/MessageText.js
Add a custom property `onPhonePress()` to deal with the action.
P.s. code based on PR #550
=> Add parsePatterns prop

README.md, example/App.js, example/data/messages.js, example/data/old_messages.js, example/yarn.lock, src/GiftedChat.js, src/Message.js, src/MessageContainer.js, src/SystemMessage.js
=> Add support for system message

src/Avatar.js, src/__tests__/__snapshots__/Message.test.js.snap, yarn.lock
=> fix(avatar): remove default

src/GiftedChat.js
=> fix(redundant): fix #704

src/Time.js
The property textStyle was missing as a parameter in the Time function
=> fixing Time textStyle issue #797

package.json
With prop-types, react and react-native and * versions.
=> add peerDependencies

src/Day.js
Resolves #789 due to a bug in PR #658.
=> Fixed Day headers when inverted prop is false

src/MessageContainer.js
Fixes videos disappearing on Android
Closes #896
=> Remove prop removeClippedSubviews on Flatlist

example-slack-message/src/App.js, example-slack-message/src/SlackBubble.js, example-slack-message/src/SlackMessage.js
This PR fixes the Slack Example by updating the PropTypes and adding an `onSend()` function to `App.js`
=> Update and Fix Slack Example

src/MessageContainer.js
It allows to override props like `style` as suggested on #795
=> Move listViewProps to the end

src/InputToolbar.js
change this.state to this.state.position
=> Fix a small error

index.d.ts
ISystemChat was defined twice leading to issues
=> Change component interface name ISystemChat to SystemChat

README.md
Add react import in main readme
Now it could be simply pasted into app without this minor bug
=> Add react import in main readme

src/MessageContainer.js
Flatlist isnt updating on renderFooter update. Hence adding extraData prop to flatList so that the ui gets updated correctly.
=> Fixing issue with flatlist as its not re-rendering on update

README.md, index.d.ts, src/GiftedChat.js, src/MessageContainer.js
This extraData prop would be helpful for re-rendering the flatlist. This is useful for rendering footer etc.
=> Flat-list re-render on demand.

example-pusher-chatkit/MyChat.js, example-pusher-chatkit/package-lock.json, example-pusher-chatkit/package.json
Updates the Chatkit example to use the latest version of the JD SDK
=> Update Chatkit example

README.md
**Update README.md**
- This is regarding the pull request in #929
=> Add renderUsernameOnMessage on the documentation

src/MessageContainer.js
To fix this: https://github.com/FaridSafi/react-native-gifted-chat/pull/1076#issuecomment-457158190
cc @ChrisEdson
=> fix MessageContainer-Pure

src/Message.js, yarn.lock
comparing objects will always return false regardless of the same value.
this will trigger unintended rerender on Message which causes performance issue.
for my case, when messages count reach a certain number, sending message becomes really slow because when appending message, it also trigger rerender on previous mesage
=> [Perf] fix shouldComponentUpdate checking on Message Component

src/Bubble.js
Inclusion of property to change the title of the displayed options when the long press bubble
=> Add bubble prop optionTitles

README.md
Put the `parsePatterns` example under parsePatterns
=> Fix the parsePatterns section of the doc

README.md
- New logo (Stream)
- Added link
=> Add Stream as sponsor

src/types.ts
Related: https://github.com/FaridSafi/react-native-gifted-chat/issues/1283
/cc @xcarpentier
=> Export props interfaces of ui components

README.md, src/GiftedChat.tsx, src/Message.tsx
Please merge this and close #1187
=> Implement shouldUpdateMessage, supersedes #1187

src/GiftedChat.tsx, src/InputToolbar.tsx, src/MessageContainer.tsx
#860 
Update componentWillMount and componentWillReceiveProps lifecycle methods.
=> Update deprecated lifecycle methods

src/GiftedChat.tsx
Add missing types to GiftedChat.tsx file.
=> fix typings for GiftedChat component

flow-typedefs/GiftedChat.js.flow, flow-typedefs/MessageContainer.js.flow, src/GiftedChat.tsx, src/MessageContainer.tsx
=> Add scrollToBottomStyle to props interface

flow-typedefs/types.js.flow, src/types.ts
=> Update weak id types

flow-typedefs/Avatar.js.flow, flow-typedefs/GiftedChat.js.flow, flow-typedefs/Message.js.flow
=> fix flow render avatar prop type

flow-typedefs/GiftedChat.js.flow, src/GiftedChat.tsx
=> Fix missing scroll to bottom component prop type

README.md
- Removed whitespace in Example snipper
- Added 2 props used to control the TextInput component that were not in the README file
=> Added textInputStyle and multiline props in the documentation.

src/Bubble.tsx, src/Message.tsx, src/__tests__/Message.test.tsx, src/__tests__/__snapshots__/Message.test.tsx.snap
=> test: Increase coverage for Message component

package.json
=> fix(test): Add coveragePathIgnorePatterns property

package.json, src/Bubble.tsx, src/GiftedChat.tsx, src/MessageText.tsx
=> Add optionTitles on MessageText & add messagesContainerStyle & fix peer dependency

src/GiftedChat.tsx
Reverts FaridSafi/react-native-gifted-chat#1524
=> Revert "adjust message container height with input toolbar/accessory height change"

flow-typedefs/Bubble.js.flow, src/Bubble.tsx
https://github.com/FaridSafi/react-native-gifted-chat/issues/1593
=> fix typings of <Bubble />

flow-typedefs/GiftedChat.js.flow
Got typescript error when using the property.
=> Added missing property: textInputStyle

src/MessageContainer.tsx
Fixed issue #1557 by changing the container of  renderChatEmpty in MessageContainer.tsc file.
=> Fixed empty chat container inverted

src/Bubble.tsx
I would like to change the order of css in the wrapper style, so the functions: this.styledBubbleToNext(),
this.styledBubbleToPrevious(), does not affect custom css
=> Order of styling for wrapper Bubble

src/GiftedChat.tsx
Adds enhancements to iPhone X support
=> Adds enhancements to iPhone X support

src/Avatar.tsx
pass textStyle prop from Avatar to GiftedAvatar to style avatar initial fonts
=> pass textStyle prop from Avatar to GiftedAvatar

README.md
- Update the documentation about message object to show developers the way to mark a message with the available states.
=> MessageObject

src/GiftedChat.tsx, src/LoadEarlier.tsx, src/MessageContainer.tsx
@xcarpentier Could you please review this changes?
Rewrite the LoadEarlier component in order to migrate to FC
Thanks, Have a nice day.
=> Refactor LoadEarlier component to FC

src/Composer.tsx, src/GiftedChat.tsx, src/InputToolbar.tsx
- Rewrite the composer in order to allow hooks.
@xcarpentier Please review the changes, when you have time.
=> Refactor Composer component to FC

src/InputToolbar.tsx
- Refactor the input toolbar component using functional components and hooks.
@xcarpentier Could you please take a look?
=> Refactor InputToolbar component to FC

src/Bubble.tsx, src/GiftedChat.tsx, src/QuickReplies.tsx
@xcarpentier Could you please review these changes?
=> Refactor QuickReplies component to FC

src/GiftedChat.tsx
=> Added renderMessageVideo property to GiftedChatProps interface

src/Models.ts
See https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/GiftedAvatar.tsx#L120
=> typings: avatar can be a number

flow-typedefs/GiftedChat.js.flow, src/GiftedChat.tsx
Related issue #1978
I added renderMessageVideo & renderMessageAudio props to GiftedChat type def.
=> Add renderMessageVideo, renderMessageAudio props to type

README.md, src/Bubble.tsx
https://github.com/FaridSafi/react-native-gifted-chat/issues/1782
=> Add onPress support for Bubble

README.md
Day.js Format - https://day.js.org/docs/en/display/format
=> Added reference to Day.js Format

example/App.tsx, src/Bubble.tsx, src/GiftedChat.tsx, src/QuickReplies.tsx
=> feat(quickreply): 🌟 add text style

example/components/navbar.tsx, src/Bubble.tsx, src/GiftedChat.tsx, src/index.ts
=> refactor(context): actionsheet & safeareaview

src/Day.tsx, src/MessageContainer.tsx, src/MessageText.tsx, src/QuickReplies.tsx, src/index.ts, src/logging.ts, src/utils.ts
This allows the defaults/constants to easily and cleanly be exported without polluting the exported modules
=> refactor(utils): split logging out and export utils

README.md
Small link change for working example
=> Update README.md example link

package.json
Fixed issue raised here: https://github.com/FaridSafi/react-native-gifted-chat/issues/2223
=> Fixed react-native-safe-area-context Dependency

example/package.json, package.json, src/Bubble.tsx, src/GiftedChat.tsx, types.d.ts, yarn.lock
This fixes `renderUsername` typescript errors, along with update a few dependencies.
=> chore(dependencies): 🔧 Update safe area view and action sheet

src/GiftedChat.tsx
Modernizes the `GiftedChat` component, which currently is written using Class component, to now be written using functional components with hooks.
- modernize `GiftedChat.tsx` component
- no breaking changes
- minimize code changes to focus on making it work with function component and hooks, rather than optimizing or doing clean ups 
- remove redundant code
- separate state
- other improvements
=> Migrate GiftedChat class component to functional component and hooks

example/example-slack-message/README.md
=> fix: img links in slack readme

README.md
Added Ethora to sponsors list in README file
=> Add ethora to sponsors list in README

README.md
Replaced old logo with the new one.
=> Ethora logo update

src/Constant.ts
Fixes react-native-windows crash
=> fix react-native-windows crash
