FaridSafi/react-native-gifted-chat

GiftedMessenger.js

Custom renderText and onSend are very useful for me.
```javascript
var HTMLView = require('react-native-htmlview');
var Chatroom = React.createClass({
...
renderCustomText(rowData, rowID) {
return <HTMLView
value={rowData.text}
onLinkPress={this._handleUrlPress}
stylesheet={{
a: {
color: (rowData.position === 'left' ? 'blue': '#fff'),
textDecorationLine: 'underline',
},
}}
/>
},
onCustomSend(message) {
this.showProgressHUD();
this.sendMessageAPI(message.text).then(response => {
this.dismissProgressHUD();
this.refs.GiftedMessenger.appendMessage(message);
this.refs.GiftedMessenger.onChangeText('');
}).catch(error => {
this.dismissProgressHUD();
AlertIOS.alert(error.message);
});
},
render() {
return (
<GiftedMessenger
ref='GiftedMessenger'
onCustomSend={this.onCustomSend} …
```

Add custom renderText and onSend

---

GiftedMessenger.js

Before if sendButton color was changed, the disabled sendButton color changed also as a side effect. This makes it possible to customize styles of both sendButton and sendButtonDisabled.

Make changing sendButton color possible w/o breaking the disabled color

---

GiftedMessenger.js

This makes it possible to render the messenger while messages are still being fetched.
Before if no messages were supplied, `allLoaded` was set to `true` assuming there are no earlier messages to be loaded. Now by setting `loadMessagesLater` flag the messenger won't make that assumption.

Add loadMessagesLater flag to props

---

GiftedMessenger.js
Message.js

- Enable sending message with return key (this should be default behavior)
- Scroll to bottom after send (the functionality is there, it's just not used atm.)
- Remove styles.imagePosition from avatar pic's TouchableHighlight (currently styles.imagePosition is used both for the Image element **and** the TouchableHighlight, which is probably a mistake)

Minor usability fixes to the UX

---

Bubble.js
GiftedMessenger.js
Message.js
README.md

Many apps want to show names inside the text bubble, rather than above it. I've added a prop `displayNamesInsideBubble`, to enable this (by setting it to true). It only does something if `displayNames` is true as well. 
Ideally both of these props would be combined in a single prop `displayNames`, which could have values such as 'no', 'inside-bubble' and 'above-bubble', but since that might break previous implementations I have chosen to make it a separate prop.

Add prop that causes names to show inside a bubble, rather than above it

---

GiftedMessenger.js
README.md

The keyboardDismissMode was provided and documented, but wasn't actually used. This has now been restored/added. 
Also, I've exposed the keyboardShouldPersistsTaps prop of the ListView, so you can now choose whether or not the keyboard will be dismissed when you tap the ListView. This should resolve #80. I realise there is an underlying issue with this (keyboardShouldPersistTaps={false} + textInput focused = 2 taps are needed to trigger the ParsedText links), but IMHO it should be up to the person using GiftedMessenger to decide what weighs heavier. In my case, I really want to close the keyboard on tapping the ListView and am willing to accept the double press for opening links. 
@FaridSafi I hope you don't mind if I keep submitting some additions to your component? :)

Fix keyboardDismissMode and add keyboardShouldPersistsTaps

---

Message.js

sometimes we don't want to store/send redundant `rowData.image = null` if we don't need it.
add this check to prevent `Required prop 'source' was not specified in 'Image'`

Message: add 'undefined' check to rowData.image

---

GiftedMessenger.js
README.md

Originally scrolling is animated but sometimes we want to disable it. Default value is true so it won't affect the original behaviour.

Add a new property `scrollAnimated` and update readme

---

GiftedMessenger.js

In 0.23.0 Warning: In next release empty section headers will be rendered. In this release you can use 'enableEmptySections' flag to render empty section headers.

Fix empty section headers warning in 0.23.0

---

GiftedMessenger.js
package.json

lodash is a large unnecessary dependency when only using a few small functions. Also, the current version on npm is broken because the newest version with [this fix](https://github.com/FaridSafi/react-native-gifted-messenger/commit/bda7ac8fe5bf41af5539cb200ab14e1aa7ae4918) has not been published.

Replace lodash with deep-equal.

---

Bubble.js

in this issues:https://github.com/FaridSafi/react-native-gifted-messenger/issues/124,i want to render my custom text.then now i can use:
rederCustomText(rowData){
if(rowData.type=='image'){
....reder CustomText
} else {
return false;
}
}

renderCustomText render if not return false value  and fix two-byte characters length error

---

src/GiftedChat.js
src/Message.js

I try to pass render custom composer param.
When i pass `multiline:false` to the composer , i got a red box.
'e.nativeEvent.contentSize' is not exist when `multiline` param set to false.
So i fix this problem. ( oh my pool english ........)

Allow pass 'multiline:false' to 'Composer' component

---

src/MessageContainer.js

`0` evaluates to `false`, so this warning will appear for anyone using a 0-based array index for their messages.
Alternative syntax could be `if (!(message._id || message._id === 0))`, if you have any particular preference for readability.

Fix unnecessary warning when message.id === 0

---

src/Bubble.js
src/Composer.js
src/GiftedAvatar.js
src/LoadEarlier.js
src/Send.js

Using `accessibilityTraits="button"`, for example, allows screen readers like Voiceover or TalkBack to behave more appropriately. See the [React Native](https://facebook.github.io/react-native/docs/accessibility.html) or [Apple](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/iPhoneAccessibility/Making_Application_Accessible/Making_Application_Accessible.html#//apple_ref/doc/uid/TP40008785-CH102-SW7) guides for more info.

Add accessibilityTraits to support screen readers

---

src/Avatar.js
src/Bubble.js
src/Day.js
src/GiftedChat.js
src/Message.js
src/utils.js

What was done:
- moved isSameUser and isSameDay functions into stand-alone utils.js file
- refactored all components that needed those functions so that they consume the new ones
- removed all code that was used to propagate the original functions through props
- removed requirements from propTypes and defaultProps

Refactor utils into stand-alone functions

---

.eslintignore
.eslintrc
package.json

Currently 486 errors, 7 warnings!
We'll have to go through and iteratively fix all of them. Most popular IDEs have an ESLint plugin where the lints will show up as red underlines, so that makes things much easier. There's also an automatic cleanup with `eslint --fix` that I haven't tried yet.
Some issues should be ignored, and that can be done line-by-line with `// eslint-disable-line rule-name` or for blocks with `/* eslint-disable rule-name */ ...code... /* eslint-enable */`
The README for [eslint-config-cooperka](https://github.com/cooperka/eslint-config-cooperka) has also been updated with config steps in case you want to have a look.

Add eslint script (extends airbnb + react + react-native)

---

README.md
src/Actions.js
src/InputToolbar.js

Optional callback when the composer's Action button is pressed (the "+" icon). If this prop is provided, it will be used instead of the default method that shows an `actionSheet`. Therefore the action sheet won't be shown at all, and your function will be called instead.
This is nice if you have your own popup you want to use, for example [react-native-image-picker](https://github.com/marcshilling/react-native-image-picker).
Tested and verified on iOS and Android.

Add 'onPressActionButton' prop

---

src/GiftedChat.js
src/MessageContainer.js

deprecated property true for keyboardShouldPersistTaps

Bug fix/update keyboard property

---

README.md
package.json
src/MessageImage.js

Images sent in messages will be enlarged when you tap them.
Also adds 2 new props: `imageProps` and `lightboxProps`. These will be passed through to the `<Image>` and `<Lightbox>`, respectively. For example, you can now specify an image [`onLoad`](https://facebook.github.io/react-native/docs/image.html#onload) callback.
Tested and verified on iOS and Android.
---
Note: Uses a commit hash instead of version number in order to fix a warning on Android that's currently unpublished.
You can read more about react-native-lightbox [here](https://github.com/oblador/react-native-lightbox) :tropical_drink:

Add lightbox for enlarging chat images

---

example/data/messages.js
src/Bubble.js
src/GiftedChat.js

I thought it would be a good idea to support ticks appearing in the bubble ala WhatsApp or Telegram depending if the message has been delivered and read.
Here is a screenshot of how it appears as of now with both the read and delivered flag set to `true`:
What do you think?

Initial support tick messages

---

src/Avatar.js

Warning: Failed prop type: Invalid prop `left` of type `object` supplied to `Avatar`, expected `number`.
Bad object: {
"left": {
"borderWidth": 1,
"borderColor": "#236CC3"
}
}

fix warning for Avatar

---

example/ios/GiftedChat/Info.plist

IOS - Example crashes when you want to choose an image via „choose from
library“ . Fixed that.  Example should work like intended.

Access to images in Library (FIXED crashes)

---

src/GiftedChat.js

Export  `GiftedAvatar` in `GiftedChat.js` so as to be able to use `GiftedAvatar` without all the logic of `Avatar`.

Expose GiftedAvatar

---

README.md
src/GiftedChat.js

This introduces a new prop : onInputTextChanged on GiftedChat API,
which is a callback function that will give whatever text is present currently in Composer back to user.
* Composer has onChange prop but it is kind of consumed by onType function in GiftedChat.js.
This will also help fix #286, where you see GiftedChat.js personally uses onChange,
and the behaviour such as height calculation would have to be performed by library user (which right now happens in onType in GiftedChat.js)
* This prop gives users a simpler interface to track change in input text, with all other features intact.
Kindly guide with suggestions/comments wherever feels necessary.
Thank you.

Add prop onInputTextChanged on GiftedChat API and help fix #286

---

package.json

npm error during gifted-chat latest version install:
npm ERR! notarget No compatible version found: md5@2.1.1
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.1, 1.0.0, 2.0.0, 2.1.0, 2.2.0, 2.2.1

fix for npm dependency

---

src/GiftedChat.js

Ran into an issue in my implementation where I have a bottom offset for the input tool bar in the chat.  When a user inputs a message, dismisses the keyboard and then sends the message, the text input tool bar would end up being rendered too low and behind a few other view components.  Instead of using the this.props.bottomOffset, it should be using this.getBottomOffset() so that it doesn't incorrectly position when the keyboard is dismissed.  Verified that sending a message with the keyboard showing still works as intended.

Reset Input Toolbar can over calculate from bottomOffset props

---

src/Bubble.js

In the bubble, there is a container that holds both the time, and the ticks. This container did not provide customization options and forced both the ticks and the time to be rendered on the right (with `flex-end`).
I created another prop, `bottomContainerStyle` that allows to customize the style of the container :)

Allow custom styling of buttom container of bubble

---

src/GiftedChat.js

After asking for permissions for the camera or gallery, then selecting a photo I get the error "null is not an object (evaluating 'this._messageContainerRef.scrollTo')" This is caused by the _messageContainerRef not having been set, which crashes the app.
This line of code fixes the issue without any side effects.
* React Native version: 0.42.0
* react-native-gifted-chat version: 0.1.3
* Platform(s) (iOS, Android, or both?): iOS

fix for _messageContainerRef === null

---

src/GiftedChat.js
src/GiftedChatInteractionManager.js

This pull request solves #350. Basically, when I was using react-native-navigation and calling a function called `resetTo` there, it simply broke the `InteractionManager` functionality, it was simply not calling the function you were passing as a parameter. More info about that [here](https://github.com/facebook/react-native/issues/8624).
Speaking about GiftedChat, I believe it's a serious problem and we should basically always display the chat. In my case, I had to debug the core of two big React Native libraries, so it would be good to merge this pull request.
A video about my bug: http://sendvid.com/qtsi7t1b
Solved now. Hope it helps you too.

InteractionManager breaks sometimes, causes hard-to-debug issues

---

src/Bubble.js

This solves the following issue: #407 
The reason of the bug was that there wasn't any default value for the newly introduced `bottomContainerStyle` property and therefore `this.props.bottomContainerStyle` is undefined if nothing is passed to the component, generating the mentioned exception when evaluating `this.props.bottomContainerStyle[this.props.position]`.

Bubble.js: Default value for prop bottomContainerStyle

---

src/GiftedChat.js

It was not exported making it harder to customize GifterChat

Export MessageContainer in GiftedChat

---

package.json

Hey @kfiroo, I've been trying to get the Call and Text options to work on highlighted phone numbers in the message text. I needed to incorporate two fixes into my fork [this](https://github.com/anarchicknight/react-native-communications/issues/31) and another PR: https://github.com/FaridSafi/react-native-gifted-chat/pull/274
Let me know what you think, thanks!

Bump react-native-communications version to 2.2.1

---

src/GiftedChat.js

This combines the fix from PR https://github.com/FaridSafi/react-native-gifted-chat/pull/280 (rebased because of merge conflicts, and @psrustik has been unresponsive) with a fix for issue https://github.com/FaridSafi/react-native-gifted-chat/issues/413.
Brief summary of issues fixed:
1. On current master, iOS screen turns blank after an orientation change, and Android jumps all over the place if the keyboard is shown before rotation
2. After the fix for orientation changes, composer height gets reset and send button goes off-screen during orientation changes (both iOS and Android)
3. Lots of duplicated math, I cleaned it up and put it into helper methods
Please see individual commits to get a better sense of the changes. Each commit is very simple on its own, though the full PR diff might …

Fix orientation change bugs

---

README.md
src/GiftedChat.js

Hi there!
I am working a React Native app that have chat feature.
This app have maximal chat text length specification (in my case is 400 chars).
So I have modify so user can set maxLength property to Composer's TextInput.

Add maxLength parameter for Composer input

---

src/utils.js

`isSameDay` method was returning `true` if we feed a `currentMessage` which is created today and an empty `diffMessage`. That is because `moment(undefined)` call will initialize the moment object to today's date. I think we were using `isValid` to make sure that there is a valid `createdAt` for `currentMessage` and `diffMessage` but `moment(undefined).isValid()` will return true.
I have changed the method to make sure that we have a valid `createdAt` date for `diffMessage` and remove the `isValid()` calls as they will always return true.

fix isSameDay function

---

README.md
src/Avatar.js

Related to issue #445 
I have added a new prop `shouldRenderAvatar` to control whether a user wants to render an avatar or not. I will document this property if the maintainers agree with the solution.

fix-extra spacing shown when avatar is not rendered

---

.gitignore
src/GiftedChat.js
src/Message.js

Simple fix: default `renderAvatar` to `undefined` instead of `null`, now that `null` causes it to not be rendered at all.
Originally mentioned in https://github.com/FaridSafi/react-native-gifted-chat/pull/447#issuecomment-305815371; see there for more context.

Fix default rendering of avatars

---

example/CustomActions.js
example/CustomView.js
src/Actions.js
src/Avatar.js
src/Bubble.js
src/Day.js
src/InputToolbar.js
src/LoadEarlier.js
src/Message.js
src/MessageImage.js
src/MessageText.js
src/Send.js
src/Time.js

[477](https://github.com/FaridSafi/react-native-gifted-chat/issues/477)

Change deprecated View.propTypes to ViewPropTypes

---

example/CustomActions.js
example/CustomView.js
package.json
src/Actions.js
src/Avatar.js
src/Bubble.js
src/Composer.js
src/Day.js
src/GiftedAvatar.js
src/GiftedChat.js
src/InputToolbar.js
src/LoadEarlier.js
src/Message.js
src/MessageContainer.js
src/MessageImage.js
src/MessageText.js
src/Send.js
src/Time.js

`React.PropTypes` is deprecated as of React v15.5. This migrates to the `prop-types` library which should have no functional consequences.

Migrate to prop-types library

---

src/MessageText.js

When someone sends a message that includes a website address beginning with "www." (omitting the scheme), `react-native-parsed-text` [recognizes it as a valid url](https://github.com/taskrabbit/react-native-parsed-text/blob/v0.0.18/src/ParsedText.js#L7), and this appears to be the intended behavior of `react-native-parsed-text`.
This is currently causing an error in `react-native-gifted-chat` because we're trying to open it directly with `Linking.openURL`, and as the react-native [Linking](https://facebook.github.io/react-native/docs/linking.html) docs indicate:
> For web URLs, the protocol ("http://", "https://") must be set accordingly
This attempts to fix the issue by inferring "http://" when no scheme is present in the URL.
Since the regex pattern used by `react-native-parsed-text` …

Fix URLs that are missing a scheme before attempting to open

---

src/MessageImage.js

Setting image to full width/height makes animation returning image to previous spot look extremely awkward. flex: 1 allows image to resize between thumbnail and fullscreen as was intended with lightbox.

flex instead of full width/height for images.

---

README.md
src/Message.js

- check if current message user has an avatar to display
- don't base the logic of the display of the avatar on the user object id
Issue: #495
Issue URL: https://github.com/FaridSafi/react-native-gifted-chat/issues/495
Screenshot with the behaviour before:
Screenshot with the behaviour after:

Add 'showUserAvatar' prop; don't render null avatars

---

src/MessageText.js

When pressing on Text, it started a call, and when pressing on call, it open the messaging app.
I just fixed the order in the options array

fixed phonePress actions order

---

src/MessageText.js

[react-native-communications](https://github.com/anarchicknight/react-native-communications) take as first argument for Communications.email a string array and not a string. I fixed this.

Fixed email recipient when clicking an email link

---

src/MessageText.js

This fixes an error in my [previous PR](https://github.com/FaridSafi/react-native-gifted-chat/pull/506) which included a check for openable URLs. `Linking.canOpenURL` returns a promise, so we need to call it accordingly.

Fix Linking.canOpenURL usage

---

src/Send.js

With this fix, you can set an image as a sender button or anything you want to.
```
renderSend(props) {
return (
<Send
{...props}
>
<View style={{marginRight: 10, marginBottom: 5}}>
<Image source={require('../../assets/send.png')} resizeMode={'center'}/>
</View>
</Send>
);
}
```

Add children props to Send component

---

README.md

the link goes to a custom action file which has no reference to onLongPress.
(the example is for the input bar)
at least link to the source file which has the default behaviour eg copy text?
cheers,

Fixed doc link for long press

---

package.json
yarn.lock

Since React 16 use `prop-types` as an external package, in order to use `PropTypes`, I've just added this in my fork.
I've made PRs on the plugins as well: 
https://github.com/taskrabbit/react-native-parsed-text/pull/34 (Merged)
https://github.com/expo/react-native-invertible-scroll-view/pull/49 (Merged)
https://github.com/oblador/react-native-lightbox/pull/75 (PR of @formula1) (Merged)

Updated dependencies for compatibility with React 16 and RN > 0.46

---

package.json

Basically, the `metro-bundler` never accepted the way moment worked with dynamic imports. But 2.19.0 fixes that and allows the lib to be used on RN >=49.0.
Read here for [more details](https://github.com/facebook/metro-bundler/issues/65#issuecomment-335524547).

Update moment to fix #597

---

src/GiftedChat.js

* adding forceGetKeyboardHeight props
* fixes https://github.com/FaridSafi/react-native-gifted-chat/issues/461
* fixes https://github.com/FaridSafi/react-native-gifted-chat/issues/518

fix(keyboard height): fix on android & expo TextInput no show

---

src/GiftedChat.js

This is a simple fix. It just turns off the inverted prop of the inverted scroll view and has new messages appended to current messages rather than the other way around.

Start messages at top

---

README.md
src/GiftedChat.js
src/MessageContainer.js

Amendment to the #489 PR allow the user to set a prop to reverse the `messages` display order on the scroll view.
**`inverted`** _(Bool)_ - Reverses display order of `messages`; default is `true`

Inverted prop for reverse messages display order

---

example/data/old_messages.js

This file was ending with 2 semicolons, this produces Unnecessary semicolon error. By this update the file is error free.

Unnecessary semicolon removed

---

src/Actions.js

Fix https://github.com/FaridSafi/react-native-gifted-chat/issues/683

fix(onPressActionButton): no default

---

src/GiftedAvatar.js

Fixes #745
Also converted `GiftedAvatar` to extend `PureComponent` instead to prevent re-rendering when props do not change at all.
<center>
| ![feb-09-2018 16-39-45](https://user-images.githubusercontent.com/1752354/36018860-3df8f2e0-0db8-11e8-9112-6580de87eeb3.gif) | ![feb-09-2018 20-48-44](https://user-images.githubusercontent.com/1752354/36028628-b3cfc5da-0dda-11e8-8a19-7909e35f1587.gif) |
|:---:|:---:|
| Before | Now  |
</center>

Fix initials not changing on user.name prop change

---

README.md
src/Avatar.js

Resolves #507 #611 
Current behaviour only shows avatars if the consecutive message's timestamp and user is different. This will allow the user to toggle avatars to always show. Defaults to `false` to maintain existing behaviour.
Usage:
```react
<GiftedChat
showAvatarForEveryMessage={true}
/>
```

Add Prop to always show avatars for each message

---

src/Composer.js

Part of personal project requires, as design dictates, to show a darker keyboard in order to comply with app's aesthetics. 
I propose a new prop within the Composer's TextInput native component, in order to make the **keyboardAppearance** property modifiable.

Add prop to modify style of keyboard shown (iOS only)

---

src/InputToolbar.js
src/__tests__/__snapshots__/InputToolbar.test.js.snap

`InputToolbar` has hardcoded width set to full screen width.
That fails when `GiftedChat` is not used full screen, part of the input is hidden:
After applying the fix, input inherits container width:

Replace hardcoded width set to full screen width

---

index.d.ts
package.json

Problems Fixed - 
* The type for `showAvatarForEveryMessage` in `GiftedChatProps` was missing in the current typedefs
* Installation of `v0.4.3`using `npm` or `yarn` was not shipping along the type definitions. Reference - https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
Detailed discussion here - #731

Added type for showAvatarForEveryMessage in index.d.ts. #731

---

index.d.ts

I noticed some trivial typos in the index.d.ts.
1. Some of the typos have no effect as they're a typo in the name of a parameter eg. `inextMessage`
2. Some of the typos are actually a mismatch in the real name of the props eg. `containertoPreviousStyle` vs `containerToPreviousStyle` -- looking at the JS code, the correct name is `containerToPreviousStyle`

Fix typos in TS Types

---

src/MessageContainer.js

This PR fixes renderFooter gifted chat prop not working with the new Flat List implementation of Message Container (#705 ).
Flat List, compared to List View used before, does not recognise `renderFooter` and `renderHeader` props, so, although they were passed, they were ignored.
This PR removes above mentioned props and utilises `ListHeaderComponent` prop which is an alternative of `renderHeader` for Flat List.

fix: enable renderFooter for FlatList MessageContainer

---

index.d.ts

Hello. 
I'm using react-native-gifted-chat with TypeScript. I want `messages` property of GiftedChat component to have a type.
I considered to write new Interface but found `IMessage` type in the type definition file. It looks good to use as type of `messages` property.
Thanks.

Use IMessage type instead of `any` to define the type of message property

---

src/Time.js
src/__tests__/__snapshots__/Time.test.js.snap

Example:
```jsx
<GiftedChat
messages={this.state.messages}
onSend={this.onSend}
renderCustomView={CustomView}
keyboardShouldPersistTaps="never"
user={{ _id: 1 }}
renderBubble={props => {
return (
<Bubble
{...props}
timeTextStyle={{
right: { color: 'red' }
}}
/>
);
}}
parsePatterns={this.parsePatterns}
/>
```
Related to #672

Add prop to customise to Text style of timestamps

---

src/MessageContainer.js

`keyExtractor` in `FlatList` must now return a string: https://facebook.github.io/react-native/docs/flatlist#keyextractor

Error in FlatList with latest react-native version

---

src/Bubble.js
src/__tests__/__snapshots__/Bubble.test.js.snap
src/__tests__/__snapshots__/Message.test.js.snap

Updating the way the bottom container is displayed based off the position of the message.
Before: 
After:

Justify Bottom Container

---

README.md
index.d.ts
src/GiftedChat.js

composer max height is currently hardcoded to 200, we will need a prop to customize this.
This is related to issue : https://github.com/FaridSafi/react-native-gifted-chat/issues/1023
Adding minComposerHeight and maxComposerHeight props to GiftedChat.
Please refer to issue : https://github.com/FaridSafi/react-native-gifted-chat/issues/1023 for screenshot.

Adding minComposerHeight and maxComposerHeight props.

---

src/MessageVideo.js

- Removes resizeMode from `videoStyle` props as this causes `Warning: Failed prop type: Invalid props.style key resizeMode`

Fixes failed prop type warning for resizeMode

---

src/GiftedChat.js

minComposerHeight is hardcoded to use constant instead of props in few instances. Due to this minimumToolbarHeight will give incorrect result thus making UI look inconsistent.
updating the code to use the props in all instances.
if we add minComposerHeight prop to the giftedChatComponent, there is a bottomOffset on keyboard open as the minInputToolbarHeight is returning incorrect value based on the hardcoded minComposerHeight.

 Updating the code to fix MinComposerHeight is not respecting props in some instances.

---

src/GiftedChat.js

Add `initialText` prop to `GiftedChat` - this gives ability to initialise chat with pre-filled value in case when you don't use `text` prop. Useful for caching input value when you re-enter chat.

Add initialText prop

---

README.md
src/GiftedChat.js
src/MessageContainer.js

Sometimes client's are fun!
My client demanded that the chat appeared at the top just like iMessage. This commit adds the option to do this.

Adds AlignTop Property

---

example-expo/CustomView.js
example-expo/NavBar.js
example-expo/app.json
example-expo/package.json
example-expo/yarn.lock

* Changed: `react-native-maps` -> expo import of `react-native-maps` (web support)
* Changed: `app.json` -> `Constants` (bare workflow support)
* Changed: Bump Expo 25 -> 32
* Changed: Bump React 16.2.0 -> 16.5.0
Ran this locally with the latest Expo client. Can confirm all functionality is still working.

[Example][Expo] Bumped Expo example version to 32

---

src/LoadEarlier.js

Pass props to customize ActivityIndicator in LoadEarlier component.

LoadEarlier ActivityIndicator props

---

src/GiftedChat.tsx

Fixes https://github.com/FaridSafi/react-native-gifted-chat/issues/1219
Every time props update (new messages, etc), the text input is cleared. This was caused by a bug during the typescript migration. It should not `setState` if `textProp` is undefined. 
Original GiftedChat.js file - https://github.com/FaridSafi/react-native-gifted-chat/commit/f2476298b983610e1af80d96c3d24328bb926f9d#diff-a2356064fe377d125c72f41f52d4dad5L141
```
setTextFromProp(textProp) {
// Text prop takes precedence over state.
if (textProp !== undefined && textProp !== this.state.text) {
this.setState({ text: textProp });
}
}
```
Migrated tsx file (with bug) - https://github.com/FaridSafi/react-native-gifted-chat/commit/f2476298b983610e1af80d96c3d24328bb926f9d#diff-81fff307db236f330955389dbb02155eR385
``` …
```

Do not setState for text if textProp is undefined

---

package.json
src/GiftedChat.tsx

As I mentioned in this issue: https://github.com/FaridSafi/react-native-gifted-chat/issues/1217. When a safeAreaView is added an extra space is added between the keyboard and the input.
This PR fixes it.

Adding support to SafeAreaView for iphoneX

---

src/Message.tsx

Same day renders several times when loading earlier messages. Аnimation below describes the problem.
```javascript
import React, {Component} from 'react';
import {View} from 'react-native';
import {GiftedChat} from 'react-native-gifted-chat';
import moment from 'moment';
export default class ChatApp extends Component {
constructor() {
super();
// Generating some message history.
this.data = [];
let createdAt = moment()
for (let i = 0; i < 100; i++) {
// We need four message per one day.
if (!(i / 2 % 2)) {
createdAt = createdAt.clone().subtract(1, 'day')
}
this.data.push({
_id: i,
text: i % 2 ? 'Namaste!' : 'Hey!',
createdAt,
user: {
_id: i % 2 ? 1 : 2,
name: i % 2 ? 'Me' : 'You'
}
})            
}
this.state = {
messages: this.data.splice(0, 2)
}
}
loadEarlier() {
// Get two more …
```

fix duplicate day rendering

---

src/Actions.tsx
src/Avatar.tsx
src/Bubble.tsx
src/Day.tsx
src/GiftedAvatar.tsx
src/GiftedChat.tsx
src/InputToolbar.tsx
src/LoadEarlier.tsx
src/Message.tsx
src/MessageContainer.tsx
src/MessageImage.tsx
src/MessageText.tsx
src/MessageVideo.tsx
src/Send.tsx
src/SystemMessage.tsx
src/Time.tsx
src/types.ts
src/utils.ts

Currently, all the components have generic props but don't actually make use of the generic, it always defaults to `IMessage`. This allows users to have a custom `Message` type (as long as it extends `IMessage`).
I also changed the utils to allow null/undefined values for diffMessage. The type of `props.previousMessage` is an optional, so we should allow passing in a potentially null/undefined value for diffMessage to make it easier/cleaner to use without having to do a check on `props.previousMessage` first.
Lastly, the type of style props should be wrapped in `StyleProp<>` in order to handle the various types of styles you can get from StyleSheet.create/inline styles, etc.

Typing improvements

---

README.md

changed renderQuickReply to renderQuickReplies in README

Wrong function name for renderQuickReplies in docu

---

README.md

Updated instructions per finding here (https://github.com/FaridSafi/react-native-gifted-chat/issues/461#issuecomment-509371173) that currently-linked solution no longer works for Android phones with notches.

Update to advice for avoiding Keyboard when using Expo

---

src/GiftedChat.tsx

Missing `props: Bubble['props']` parameter definition in `renderCustomView()`

Fix `renderCustomView` Typescript definition.

---

README.md

With the current instructions, the keyboard will hide the chat view.
With the new instructions, the keyboard will push the chat view as intended.

docs(README): Update KeyboardAvoidingView instructions

---

src/MessageContainer.tsx

There was a visual glitch whenever using Ionicons or FontAwesome Icons instead of the default Text arrow, erasing half of the icon used. By removing that unnecessary padding it solved it.
Also, added the customization for the icon wrapper (scrollToBottomContainer) that was missing before. Now you can override any default styling for this.

This PR fixes some scrollToBottom visual glitch and adds wrapper custom styling 

---

README.md
flow-typedefs/GiftedChat.js.flow
src/GiftedChat.tsx

This PR incorporates #1171, #1326  by adding the `isKeyboardInternallyHandled` prop. When set to true, a KeyboardAvoidingView is added from react-native in order to make the animation smoother on the textbox above the keyboard.
When the prop is set to false, there is only a View with no animation. This gives the option for users to use their own keyboard handlers.
Also to address @llamaluvr concerns about offering an offset prop for people's chrome. This  prop was never needed because the keyboard avoider only smooths the animation, it doesn't actually handle the keyboard.
Let me know if you have any questions.

Improve keyboard performance revisited

---

README.md
src/GiftedChat.tsx
src/MessageContainer.tsx

This PR implements renderChatEmpty prop on GiftedChat component to allow rendering custom empty view for when the messages prop are empty.
When no value is set, it renders a default empty container view with `flex: 1`, which behaves similarly to the previous implementation but with one difference. The empty view is now always rendered in ListEmptyComponent to allow dismissing keyboard by tapping the empty view just like when the messages are displayed in the MessageContainer.
Unfortunately, due to a bug in some React Native versions including the latest,
when `inverted={false}` is specified in `<GiftedChat>` component and the internal FlatList is inverted, 
the ListEmptyView is rendered upside down (See https://github.com/facebook/react-native/issues/21196
).
I believe the bug should be …

Implement renderChatEmpty for when messages are empty

---

src/Composer.tsx
src/GiftedChat.tsx

Fix disableComposer Issue, Disabled composer user can only view the chat can't respond.
Issue Reference [Temporarily disable TextInput #1554](https://github.com/FaridSafi/react-native-gifted-chat/issues/1554)

add disableComposer prop

---

README.md

componentWillMount() is deprecated since React Native 0.54 / ReactJS 16.3, replaced it with componentDidMount() in the example to prevent confusion

Updated deprecated lifecycle method in README

---

src/GiftedChat.tsx

Currently the message container height reamins the same & does not update/adjust with input toolbar/custom accessory height change. The related issue - https://github.com/FaridSafi/react-native-gifted-chat/issues/911.
This PR will update the message container height if the input toolbar height is updated.

adjust message container height with input toolbar/accessory height change

---

README.md

- In README.md Line304, It seems to be missing `` ` `` before  `image props`.  So README is not drawn correctly.
- before : <img width="862" alt="スクリーンショット 2019-12-28 18 29 21" src="https://user-images.githubusercontent.com/14814057/71541844-478bb380-29a2-11ea-8012-1a2d37bffd17.png">
- after : <img width="825" alt="スクリーンショット 2019-12-28 18 28 51" src="https://user-images.githubusercontent.com/14814057/71541842-3d69b500-29a2-11ea-990a-0f9cd3f3a208.png">

Fix REDME.md 

---

src/MessageContainer.tsx

I got a crash when using this component in React Native, the crash report is:
```
User comment: opened a conversation then immediately pressed back; app had just opened from phone sleep
Stack trace from JavaScript:
com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't.props.forwardRef.current.scrollToEnd'), stack:
scrollToBottom@1272:2683
<unknown>@1272:4090
y@115:661
callTimers@115:2718
value@28:3685
<unknown>@28:841
value@28:2939
value@28:813
value@-1
```
I just added an if guard. Notice that the line above that calls the `scrollTo` method is actually guarded against nulls (see the implementation of `scrollTo`), but for some reason this line 240 wasn't guarded. I think this is a harmless addition.
PS: thanks for react-native-gifted-chat! Really …

fix null ref case in MessageContainer

---

src/Actions.tsx
src/Avatar.tsx
src/Bubble.tsx
src/Day.tsx
src/InputToolbar.tsx
src/LoadEarlier.tsx
src/Message.tsx
src/MessageImage.tsx
src/MessageText.tsx
src/Send.tsx
src/SystemMessage.tsx
src/Time.tsx

ViewPropTypes is no longer supported on react-native-web > 0.12.0 as described on this issue https://github.com/necolas/react-native-web/issues/1537

Remove ViewPropTypes references to support react-native-web >= 0.12.0

---

src/GiftedChat.tsx

This fix is needed, because the current implementation (which triggers on keyboardWillHide for example when you start doing a gesture swipe back gesture and abort it (or when you open the ActionSheet while having focus on input) takes "bottomOffset" parameter, or getBottomSpace (which is always 34). It should check if an actual bottomOffset is set and take that value instead, without it, it breaks custom InputToolbar heights.
It should not break anything, it should fix issues on iPhone X+

Update bottomOffset, fix issues on iPhone X

---

package.json

Due to the fixed version of dayjs in the package.json, if you are using another version of dayjs in your package.json application, a copy of dayjs is added in the node_modules of dayjs (transitive dependencies).
Due to this is not possible to load locale files for dayjs in an application, because gifted chat as another instance of dayjs.
The dayjs version must be flexible.
In a more recent commit I saw that you change it to 1.8.27 so people using 1.8.26 willl have the problem.

DayJS should not have a fixed version in package.json (Duplicate DayJS instance)

---

src/GiftedChat.tsx

Fixes https://github.com/FaridSafi/react-native-gifted-chat/issues/1809

Avoid setting heights twice within 0.1s

---

README.md

**For new folks** there are some missing steps and could be confusing.
I was trying to setup for local development and after looking at `yarn add -g expo-cli` get the following command error:
Maybe this PR helps to prevent that.

fix: local development setup

---

src/GiftedChat.tsx

I faced an issue with opened keyboard `bottomOffest` when an action sheet opened and then closed. When I deep into the code, I found that in this case `onKeyboardWillShow` is called two times (as shown in the first video). The issue happens because the two events fired in sequence without`onKeyboardWillHide` event in between so the calculations is failed. As I understood the `safeAreaSupport` should return the `bottomOffest` prop if provided, otherwise return the bottom safe are. Therefore, I adjust it to adapt this logic and this fixed the issue. Actually, I don't sure if my understanding is right so I don't know if there's another cases this will be fail or not 😅
The same issue happens when the chat is empty. I found the reason is that the keyboard events is registered in two places in …

Fix bottom offset issue

---

src/MessageContainer.tsx

In case if the chat is empty, two keyboard listeners is registered (One in `MessageContainer` and the other in the rendered `FlatList`). I think we don't need the `MessageContainer` one since the `FlatList` one is already fired even if it is empty.

[Refactor] Remove unnecessary keyboard listener in empty chat

---

src/GiftedChat.tsx

The issue happens during opening image picker and the text input is already focused. In this case, the text input lost its focus after opening the picker so when the picker closed we can't dismiss the keyboard by tapping on container so we need to re-focus the text input. The steps to produce the issue are in this [Video](https://www.dropbox.com/s/8impa23i6la3n66/keypersist.mp4?dl=0&raw=1) (Thanks to @xcarpentier)

[Fix] Keyboard persist taps issue after selecting image

---

src/GiftedChat.tsx

According to [documentation](https://github.com/FaridSafi/react-native-gifted-chat#props), `renderAvatar` should accept null.

Change typing of renderAvatar to support null

---

src/MessageContainer.tsx

Fixes #1826. Proptypes should now line up with how extraData is consumed in MessageContainer.

Change proptype of extraData in MessageContainer

---

src/Day.tsx

This PR adds the ability of us passing specific props directly to the `Text` component used on `Day.tsx`. This is especially useful when we need to use something as `maxFontSizeMultiplier` for example.

Add textProps to Day component

---

src/Models.ts

I found the issue when i want to change just only one param it will give error so
i just changed it to `?` optional `param` of  
```
export interface LeftRightStyle<T> {
left?: StyleProp<T>;
right?: StyleProp<T>;
}
```
solved #1984

`LeftRightStyle` should be an optional param

---

package.json
src/Message.tsx
yarn.lock

- Update `react-native-iphone-x-helper` to support iPhone 12 series devices
- Add `onMessageLayout` prop to get the message layout. This is useful if we need to implement scrolling to specific message.

Support iPhone 12 series and message layout prop

---

src/MessageContainer.tsx

Fix for `infiniteScroll` issue #1928
Run the `onLoadEarlier` even when hitting the edge, but not when initially opening the chat (user scroll has to happen first)

* fix infiniteScroll issue #1928

---

example/package.json
example/yarn.lock
package.json
src/MessageContainer.tsx
src/MessageImage.tsx
src/types.d.ts
yarn.lock

This is a fix to get rid of the warnings. 
Ideally, we shift the responsibility to the user of the library.
That way they can decide which library to use.. i.e. lightbox v2, some reanimated2 implementation, etc.
This is a good default though.

refactor(lightbox): 🔨 use v2 instead

---

example/package.json
example/yarn.lock
package.json
src/MessageText.tsx
yarn.lock

Removes `react-native-communications` in favour of using the built-in linking functionality.

refactor(linking): 🔨 remove react-native-communications and use native linking

---

package.json
yarn.lock

Updates use-memo-one to latest (1.1.2) which supports react 17
Closes GH-2200

chore(use-memo-one): update to support react 17

---

src/QuickReplies.tsx

- Return null when !shouldComponentDisplay after the useCallbackOne hook
- Closes #2216

Fix: QuickReplies component is returning null before a react hook & breaking rules of hooks.

---

flow-typedefs/Bubble.js.flow
flow-typedefs/GiftedChat.js.flow
flow-typedefs/QuickReplies.js.flow
src/Bubble.tsx
src/GiftedChat.tsx
src/QuickReplies.tsx

- Currently we can not pass custom message to the QuickReply component due to it type constraint allowing it to use IMessage only.
- This PR enables use of custom message type TMessage similar to other components like MessageImage & also makes it consistent.

Fix: allow custom message type TMessage for quickReply props similar to MessageImage,  etc.

---

README.md
src/Bubble.tsx
src/GiftedChat.tsx

We have the prop `renderUsername` but didn't use it before and we can't custom username's view. So I just return the `renderUsername` to allow custom username's view

Support renderUsername

---

example/App.tsx
example/components/navbar.tsx
package.json
src/GiftedChat.tsx
tests/setup.js

This is a proposal PR to remove the need to use `react-native-safe-area-context` as a dependency. From experience, it seems most developers handle `<SafeAreaView>`'s on their own terms. 
Furthermore, based on what I see, the GiftedChat library is currently using SafeAreaView so that the Example app can have spacing, but beyond that it doesn't seem to offer much more benefit or is a necessary thing.
In addition, a good chunk of issues are caused by GiftedChat trying to apply SafeAreaView without this being documented. Though I now see a PR by someone else for that https://github.com/FaridSafi/react-native-gifted-chat/pull/2336
Because the SafeAreaView dep is not being updated it often causes problems such as:
- https://github.com/FaridSafi/react-native-gifted-chat/issues/2349
- …

ref!: remove react-native-safe-area-context dependency

---

src/GiftedChat.tsx

Applying the `bottomOffset` prop was inadvertently removed in the PR to remove the react-safe-area-context dependency [#2353](https://github.com/FaridSafi/react-native-gifted-chat/pull/2353)  The `bottomOffset` props is often used when using React Navigation tabs for iOS to remove the gap created between the input/chat and keyboard. This PR restores the previous functionality of the `bottomOffset` prop.
Prior to this PR the `bottomOffset` prop was always applied when the `onKeyboardWillShow` event was fired. This happened regardless if gifted chat was wrapped in a safe area or not.
https://github.com/FaridSafi/react-native-gifted-chat/blob/75e75f0a7916379e7b4a3f3c25e8360f1e856d17/src/GiftedChat.tsx#L638
https://github.com/FaridSafi/react-native-gifted-chat/blob/75e75f0a7916379e7b4a3f3c25e8 …

(fix) Apply bottomOffset when keyboard is shown

---

src/GiftedChat.tsx

Fixes #2370 by saving the context as a state object so the object doesn't change. Currently whenever the GiftedChat component re-renders it causes the context to change as the context is given a new value. this causes all the components that rely on the context to update, which is a lot of them.

Prevent the context from changing which forces unnecessary rerenders

---

src/GiftedChat.tsx

The `renderAvatar` prop must accept `null` as value to prevent issues like #2274.
`null` was included in the union type of the `renderAvatar` return value, and thus was not caught by [this TS rule](https://github.com/microsoft/TypeScript/pull/39570)

Fixes null type for renderAvatar prop

---

README.md

This PR fixes the broken path to example-slack-chat in README.md.
Yup, that's it.

chore(README): Fix broken path to example-slack-chat

---

src/MessageImage.tsx

There is currently no way to add additional headers to the image shown in `MessageImage`. This can be an issue if you need to add credentials to the header when making a request, for instance.
Usage: 
```tsx
<MessageImage
{...props}
imageSourceProps={{
headers: {
Authorization: `Bearer ${authToken}`
}
}}
/>
```

Add `imageSourceProps` to `MessageImage`

---

flow-typedefs/Bubble.js.flow
flow-typedefs/GiftedChat.js.flow
flow-typedefs/QuickReplies.js.flow
src/Bubble.tsx
src/GiftedChat.tsx
src/QuickReplies.tsx

Feat: Allow QuickReplies component container styles to be customised

---

src/Avatar.tsx

Warning: Avatar: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead
closes #2498

fix: avatar defaultProps warning

---

src/GiftedChat.tsx

renderUsernameOnMessages added to GiftedChatProps

Added removed property from previous patches which resulted not to work on typescript projects

---

src/MessageContainer.tsx

I don't understand why this condition is existing.
There is no way to show the typing indicator on the web platform if this condition is here.
I suggest to remove this condition to allow developer to show this indicator

Show typing indicator on web platform

---

README.md
src/GiftedChat.tsx

Fix #2522
More information: https://docs.swmansion.com/react-native-reanimated/docs/device/useAnimatedKeyboard#remarks

Add `isStatusBarTranslucentAndroid` to prevent status bar from changing color

---

src/GiftedChat.tsx

This PR resolves an issue with focus handling when opening the keyboard. I discovered that when an input field inside a modal on the chat page receives focus, the focus was incorrectly being intercepted by the chat input. The check for `isTextInputWasFocused: MutableRefObject<boolean>` was incorrect, so it has been replaced with a value check.
All tests have passed successfully. However, given my limited experience with this library, I would appreciate it if someone familiar with the project could review this change to ensure it doesn't unintentionally alter any critical behavior.
Let me know if you want any changes to it

fixed: focus handling when opening keyboard

---

README.md
src/GiftedChat.tsx

Solves issues: https://github.com/FaridSafi/react-native-gifted-chat/issues/2548 and https://github.com/FaridSafi/react-native-gifted-chat/issues/2572

Add `focusOnInputWhenKeyboardOpens` prop to disable focus on `<TextInput />` when opening the keyboard

---

src/GiftedChat.tsx

After adding support for `bottomOffset` I found some case on iOS:
When we first open the keyboard on iOS we skip the animation logic because `prevValue` is `0`:
```
value 260
prevValue 0
// (prevValue && value !== prevValue) is false
```
We don't see this issue on Android, as the keyboard gets a bunch of values ​​when first opened:
```
value 0
prevValue 0
// (prevValue && value !== prevValue) is false
value 18
prevValue 0
// (prevValue && value !== prevValue) is false
value 50
prevValue 18
// (prevValue && value !== prevValue) is true
```
(all of these triggers above are triggered on first press)
`prevValue` can be `null` or a number, and I couldn't understand why we check `prevValue` instead of `prevValue !== null`, so I changed this condition.

Fix initial keyboard animation if `prevValue` is `0`

---

src/InputToolbar.tsx

This add the `onPressActionButton` as props to `Actions` elements
Fix https://github.com/FaridSafi/react-native-gifted-chat/issues/2560

fix onPressActionButton not being called

---

src/Bubble/index.tsx

PR #2609 introduced a type regression by migrating the Bubble component from a class component to a function component using React.FC, which does not support generics.
This commit replaces `React.FC` with generics and a `JSX.Element` return type on the Bubble component, allowing to keep the function component and bringing back the type argument. The type argument here is necessary to provide accurate type information for non-vanilla messages.
Since generics are used quite extensively on this project especially around message object customization, I recommend to steer away from using `React.FC` for consistency's sake.
For those wanting to use a ready-to-go patch using patch-package for example, here you go:
<details>
<summary>
react-native-gifted-chat+2.8.1.patch
</summary>
```patch
diff …
```

Fix: Bubble component typing regression
